name: Pr

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the master branch
permissions:
  actions: read
  contents: read

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: jdx/mise-action@3bc85396a273ed82bba5e53a15174bbf9dba095c
        with:
          version: 2023.12.0 # [default: latest] mise version to install
          install: true # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache
          log_level: debug # [default: info] log level

      - name: Install Python Packages
        uses: ./.github/actions/setup-poetry

      - name: lint
        run: just lint

      - name: test
        run: |
          just unittest
          just build
          just integrationtest

      - name: docs
        run: just docs
