name: Release

on:
  push:
    branches:
      - master

env:
  HUSKY: 0 # https://typicode.github.io/husky/how-to.html#ci-server-and-docker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the master branch
permissions:
  actions: read
  contents: write
  deployments: write
  pull-requests: write
  id-token: write

jobs:
  Process:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      prs_created: ${{ steps.release-please.outputs.prs_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          token: ${{secrets.RELEASE_PLEASE_TOKEN}}
      - name: Print Release Data
        run: |
          echo 'Release Data:'

          echo '''
            ${{ toJSON(steps.release-please.outputs) }}
          '''

  Deploy:
    needs: Process
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/PACKAGE_NAME
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: jdx/mise-action@3bc85396a273ed82bba5e53a15174bbf9dba095c
        with:
          version: 2023.12.0 # [default: latest] mise version to install
          install: true # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache
          log_level: debug # [default: info] log level

      - name: Poetry
        uses: ./.github/actions/setup-poetry

      - name: Preflight
        run: |
          just lint
          just types
          just unittest
          just build
          just integrationtest

      - if: ${{ needs.Process.outputs.releases_created == 'true' }}
        uses: |
          just publish

      - if: ${{ needs.Process.outputs.prs_created == 'true' }}
        run: |
          echo 'PRs created, but no releases. Skipping publish.'
